### ISSUE TITLE
Unable to wrap NTEnum with display options

### ISSUE THREAD

**Issue by kathryn-baker** [mdavidsaver/p4p#120]
Hi there, 

I am trying to create NTEnum type PVs that have a description using the following code:
```python
import time

from p4p.client.thread import Context
from p4p.nt import NTEnum, NTScalar
from p4p.server import Server
from p4p.server.thread import SharedPV

from server.handlers import EnumHandler, Handler

display = {
    "display.units": "V",
    "display.format": "f6",
    "display.description": "test desc",
}

nt_enum = NTEnum(display=True, valueAlarm=True, control=True)
nt_scalar = NTScalar(display=True, valueAlarm=True, control=True)

enum_value = {"choices": ["false", "true"], "index": 1}
enum_value.update(display)

pv_enum = SharedPV(
    nt=nt_enum,
    initial=enum_value,
    handler=EnumHandler(name="test"),
)

scalar_value = {"value": 5.0}
scalar_value.update(display)
pv_scalar = SharedPV(nt=nt_scalar, initial=scalar_value, handler=Handler(name="test"))

providers = {
    f"TEST:PV:STATUS": pv_enum,
    f"TEST:PV:VALUE": pv_scalar,
}
server = Server.forever([providers])
```
However the creation of the PV fails with the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/p4p/server/raw.py", line 158, in open
    V = self._wrap(value, **kws)
  File "/usr/local/lib/python3.10/site-packages/p4p/nt/enum.py", line 71, in wrap
    V.value = value
  File "src/p4p/_p4p.pyx", line 223, in p4p._p4p._Value.__setattr__
KeyError: "no such member 'display.units' in 'display.units'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/src/app/src/nt_tests.py", line 33, in <module>
    pv_enum = SharedPV(
  File "/usr/local/lib/python3.10/site-packages/p4p/server/thread.py", line 76, in __init__
    _SharedPV.__init__(self, **kws)
  File "/usr/local/lib/python3.10/site-packages/p4p/server/raw.py", line 140, in __init__
    self.open(initial, nt=nt, wrap=wrap, unwrap=unwrap, **kws)
  File "/usr/local/lib/python3.10/site-packages/p4p/server/raw.py", line 160, in open
    raise ValueError("Unable to wrap %r with %r and %r"%(value, self._wrap, kws))
ValueError: Unable to wrap {'choices': ['false', 'true'], 'index': 1, 'display.units': 'V', 'display.format': 'f6', 'display.description': 'test desc'} with <bound method NTEnum.wrap of <p4p.nt.enum.NTEnum object at 0x7f52ae397e50>> and {}
```

Both handlers imported use the following code in the `put()` method:
```python
def put(self, pv, op):
    pv.post(op.value(), timestamp=time.time())
    op.done()
```

The NTScalar PV is created without any errors. 

I am using p4p version 4.1.10 with python 3.10.12

**Comment by mdavidsaver** [comment]
> KeyError: "no such member 'display.units' in 'display.units'"

Ok, this error is slightly confusing.  The meaning is that there is no such member field X when evaluating expression Y.

`NTEnum` does not have `display.units` by default.  Of course, extra fields can be added.

```py
NTScalar('i', display=True, extra=[
    ('display', ('S', None, [
        ('units', 's'),
    ]))
])
```

**Comment by kathryn-baker** [comment]
It's useful to know they don't have units by default, thanks! I got the same error when just trying to add a description (no units or format) though, is that the expected behaviour as well?

**Comment by mdavidsaver** [comment]
With `p4p==4.1.10` `NTEnum` should have `display.description`.  Actually, `display.units` should be there as well...  Including `units` and `limit*` was an oversight on my part.  I don't think they make sense for an enumeration.  But I will leave them.

https://github.com/mdavidsaver/p4p/blob/37747cf1c495e997a4c4bf67a8eba9a37c50a665/src/p4p/nt/scalar.py#L137-L143

```py
from pprint import pprint
from p4p.nt import NTEnum
pprint(NTEnum.buildType(display=True).aspy())
```
Should print:
```
('S',
 'epics:nt/NTEnum:1.0',
 [('value', ('S', 'enum_t', [('index', 'i'), ('choices', 'as')])),
  ('alarm',
   ('S', 'alarm_t', [('severity', 'i'), ('status', 'i'), ('message', 's')])),
  ('timeStamp',
   ('S',
    'time_t',
    [('secondsPastEpoch', 'l'), ('nanoseconds', 'i'), ('userTag', 'i')])),
  ('display',
   ('S',
    'structure',
    [('limitLow', 'i'),
     ('limitHigh', 'i'),
     ('description', 's'),
     ('format', 's'),
     ('units', 's')]))])
```

**Comment by kathryn-baker** [comment]
Thanks, I've swapped to using the `buildType` notation and am getting the structure that I am after now!
