### ISSUE TITLE
Tests fail with ImportError

### ISSUE THREAD

**Issue by anderslindho** [mdavidsaver/p4p#142]
Following the instructions in the README (as well as in `docs/building.rst` under "Local (re)build as Python package", regardless if I install from pypi or directly from source), I get the following failure:
```
E
======================================================================
ERROR: p4p (nose2.loader.LoadTestsFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anderslindh/p4p/src/p4p/__init__.py", line 14, in <module>
    from .wrapper import Value, Type
  File "/home/anderslindh/p4p/src/p4p/wrapper.py", line 5, in <module>
    from . import _p4p
ImportError: cannot import name '_p4p'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

This on a centos7 machine with python 3.6.8 and
```
Cython==3.0.10
epicscorelibs==7.0.7.99.0.2
nose2==0.13.0
numpy==1.19.5
p4p @ file:///home/anderslindh/p4p
ply==3.11
pvxslibs==1.3.1
setuptools-dso==2.10
```

**Comment by mdavidsaver** [comment]
> File "/home/anderslindh/p4p/src/p4p/__init__.py", line 14, in <module>

When I run into an error like this, it is usually because I have run `nose` in a directory with an incomplete build of p4p.  eg. a git clone after I have `pip install .`

For a Makefile build, `make nose` will adjust `PYTHONPATH` accordingly.  For a `pip` install, this is the (unstated) reason why the "Python package" section of `docs/building.rst` does not include a `git clone`.
