### ISSUE TITLE
PV put syntax for nested structure

### ISSUE THREAD

**Issue by ifmalcuaz** [mdavidsaver/p4p#35]
Hi @mdavidsaver,

I have a PV with a nested hierarchy as follows:

```
structure
    structure arg1
        int value
    structure arg2
        int value
    structure operation
        string value
    structure result
         int value
```

I want to do a put to all of its fields simultaneously; using the command line pvput from epics base I can do so via:

```
$ pvput -r "field()" calcPV arg1='{"value":1}' arg2='{"value":1}' operation='{"value":"+"}'
```

Is this possible with p4p with just one put? I've tried:

```
CTXT = Context("pva")
CTXT.put("calcPV", [{"arg1.value": 1}, {"arg2.value": 1}, {"operation.value":"+"}])
```

which throws a RemoteError as it's probably unimplemented:

```
Traceback (most recent call last):
  File "/scratch/tph19377/EPICS_REPOS/p4p/python2.7/linux-x86_64/p4p/client/raw.py", line 113, in builder
    V.value = value
AttributeError: 'Value' object has no attribute 'value'
Traceback (most recent call last):
  File "../client/p4p/sample_pva_client.py", line 177, in <module>
    calc()
  File "../client/p4p/sample_pva_client.py", line 157, in calc
    dummy_plus_operation}])
  File "/scratch/tph19377/EPICS_REPOS/p4p/python2.7/linux-x86_64/p4p/client/thread.py", line 364, in put
    raise value
p4p.client.raw.RemoteError: PyErr during builder callback
```

As a workaround I have to put to the individual fields separately like so:

```
CTXT = Context("pva")
CTXT.put("calcPV", {"arg1.value": 1})
CTXT.put("calcPV", {"arg2.value": 1})
CTXT.put("calcPV", {"operation.value":"+"})
```
Which works fine, however is there cleaner option without having to build the query manually with p4p.Value and p4p.Type?

**Comment by mdavidsaver** [comment]
I guess the documentation of `Context.put` needs some improvement.  One way to put to multiple fields is:

```python
CTXT = Context("pva")
CTXT.put("calcPV", {"arg1.value": 1,
                    "arg2.value": 1,
                    "operation.value":"+"})
```

**Comment by ifmalcuaz** [comment]
Thanks!
